#!/bin/sh -ex

SRC=/usr/local/src
SDKROOT=/var/www/senchasdk
SDKTOOLS=/usr/local/share/senchasdktools

# unpack and install
unzip $SRC/sencha-touch-*.zip -d $(dirname $SDKROOT)
mv $(dirname $SDKROOT)/sencha-touch-* $SDKROOT
rm $SRC/sencha-touch-*.zip
chown -R root:root $SDKROOT

chmod +x $SRC/SenchaSDKTools-*
$SRC/SenchaSDKTools-* --unattendedmodeui none --mode unattended --prefix $SDKTOOLS
rm $SRC/SenchaSDKTools-*

# install compress (sass css) and add rubygems bin to path
cd $SRC/gems
gem install --local --no-rdoc --no-ri *.gem
rm -rf $SRC/gems

cat >/etc/skel/.bashrc.d/rubygems<<EOF
PATH="/var/lib/gems/1.8/bin:\$PATH"
EOF
chmod +x /etc/skel/.bashrc.d/rubygems
cp /etc/skel/.bashrc.d/rubygems /root/.bashrc.d/rubygems

# configure apache
rm /etc/apache2/sites-available/default-ssl
a2enmod rewrite
rm /var/www/index.html
