#!/bin/sh -ex

SRC=/usr/local/src
WEBROOT=/var/www/sencha
S_CMD=/usr/local/share/senchacmd

# unpack and install
unzip -q $SRC/sencha-touch-*.zip -d $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/touch-* $WEBROOT
rm $SRC/sencha-touch-*.zip
chown -R root:root $WEBROOT

unzip -q $SRC/SenchaCmd-*.run.zip -d $SRC
$SRC/SenchaCmd-*.run --unattendedmodeui none --mode unattended --prefix $S_CMD
rm $SRC/SenchaCmd-*

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
gem install compass
unset HTTP_PROXY

cat >/etc/skel/.bashrc.d/rubygems<<EOF
PATH="/var/lib/gems/1.8/bin:\$PATH"
EOF
chmod +x /etc/skel/.bashrc.d/rubygems
cp /etc/skel/.bashrc.d/rubygems /root/.bashrc.d/rubygems

# configure apache
rm /etc/apache2/sites-available/default-ssl
a2enmod rewrite
rm /var/www/index.html
